ve in #rohtak, haryana but for your information every where in haryana pani puri are known as gol gappa like any where else in northern India...
in some rural parts ppl may refer these as puchka but not in entire Haryana...
Please do some more search before posting such an idiotic sentences in your post
Reply · Like · 1 · Follow Post · March 12 at 4:21pm
